# Generated by Django 4.2.7 on 2023-12-20 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0004_museum_address_en_museum_address_ru_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('name_en', models.CharField(blank=True, max_length=100, null=True)),
                ('name_uz', models.CharField(blank=True, max_length=100, null=True)),
                ('name_ru', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, max_length=100, null=True)),
                ('description_en', models.TextField(blank=True, max_length=100, null=True)),
                ('description_uz', models.TextField(blank=True, max_length=100, null=True)),
                ('description_ru', models.TextField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.CharField(blank=True, max_length=100, null=True)),
                ('date_time', models.CharField(blank=True, max_length=100, null=True)),
                ('images', models.ImageField(help_text='Image', null=True, unique=True, upload_to='files/covers')),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.CharField(blank=True, max_length=100, null=True)),
                ('images', models.ImageField(help_text='Image', null=True, unique=True, upload_to='files/covers')),
            ],
        ),
        migrations.RemoveField(
            model_name='visit',
            name='museum',
        ),
        migrations.DeleteModel(
            name='Museum',
        ),
        migrations.DeleteModel(
            name='Visit',
        ),
    ]
