# Generated by Django 4.2.7 on 2023-12-20 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0005_banner_partner_remove_visit_museum_delete_museum_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('title_en', models.CharField(blank=True, max_length=100, null=True)),
                ('title_uz', models.CharField(blank=True, max_length=100, null=True)),
                ('title_ru', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, max_length=100, null=True)),
                ('description_en', models.TextField(blank=True, max_length=100, null=True)),
                ('description_uz', models.TextField(blank=True, max_length=100, null=True)),
                ('description_ru', models.TextField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('work_time', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('messenger_url', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
