# Generated by Django 4.2.7 on 2023-12-20 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0007_about_address_en_about_address_ru_about_address_uz_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('first_name_en', models.CharField(blank=True, max_length=100, null=True)),
                ('first_name_uz', models.CharField(blank=True, max_length=100, null=True)),
                ('first_name_ru', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.TextField(blank=True, max_length=100, null=True)),
                ('last_name_en', models.TextField(blank=True, max_length=100, null=True)),
                ('last_name_uz', models.TextField(blank=True, max_length=100, null=True)),
                ('last_name_ru', models.TextField(blank=True, max_length=100, null=True)),
                ('bio', models.CharField(blank=True, max_length=100, null=True)),
                ('bio_en', models.CharField(blank=True, max_length=100, null=True)),
                ('bio_uz', models.CharField(blank=True, max_length=100, null=True)),
                ('bio_ru', models.CharField(blank=True, max_length=100, null=True)),
                ('telegram', models.CharField(blank=True, max_length=100, null=True)),
                ('instagram', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='banner',
            name='comic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='museum.comic'),
        ),
    ]
