# Generated by Django 4.2.7 on 2023-12-21 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0009_alter_comic_bio_alter_comic_bio_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eat_Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, max_length=100, null=True)),
                ('price', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
